name: Daily Auto Commit

# Pemicu: Jalankan setiap hari pada jam 00:00 UTC (07:00 WIB)
on:
  schedule:
    - cron: '0 0 * * *'
  # Baris di bawah ini untuk testing manual, bisa dihapus nanti
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Dapatkan token akses untuk GitHub App kita
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      # Langkah 2: Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Kita gunakan token dari App agar bisa push commit nanti
          token: ${{ steps.generate_token.outputs.token }}

      # Langkah 3: Buat perubahan pada file
      - name: Modify a file
        run: |
          # Contoh: Menulis tanggal dan waktu saat ini ke sebuah file
          echo "Last update on $(date)" > last_update.txt

      # Langkah 4: Lakukan commit dan push
      - name: Commit and push changes
        run: |
          git config --global user.name "Proyek Gede AutoCommit Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add .
          # Cek jika ada perubahan sebelum commit, untuk menghindari error
          if ! git diff --staged --quiet; then
            git commit -m "docs: Daily update"
            git push
          else
            echo "No changes to commit."
          fi
          
